category:
  highest_level: 1
  middle_level: 2
  lowest_level: 3
  home_block_1: 1
  home_block_2: 2
blog_category:
  news: 1
limit:
  catalog: 2
  brand_logo: 12
  blog_home_page: 4
  product_field: 10
  product_block: 4
  related_products: 4
  new_products: 3
  paginate:
    products: 16
    blogs: 5
    documents: 10
    videos: 10
    admin_blog: 10
  menu_block:
    a_to_z: 3.0
    brand: 4.0
  label_block: 10
  category_home_block: 12
  home_block_element: 2
  home_block_category: 4
format:
  created_at: "%d/%m/%Y"
media_type:
  document: 0
  video: 1
production_host: "thietbithinghiem.top"
